[package]
name = "mc-sgx-tservice-sys-types"
version = "0.6.0"
authors = { workspace = true }
# See https://crates.io/category_slugs for valid categories
categories = ["external-ffi-bindings", "hardware-support", "no-std"]
description = "FFI type definitions for `sgx_tservice`."
edition = { workspace = true }
# See https://crates.io/keywords for the common keywords
keywords = ["ffi", "sgx", "no-std"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }

[lib]
doctest = false

[dependencies]
mc-sgx-core-sys-types = { path = "../../../core/sys/types", version = "=0.6.0" }
mc-sgx-tcrypto-sys-types = { path = "../../../tcrypto/sys/types", version = "=0.6.0" }

[build-dependencies]
bindgen = "0.65.1"
cargo-emit = "0.2.1"
mc-sgx-core-build = { path = "../../../core/build", version = "=0.6.0" }
