[package]
name = "mc-sgx-dcap"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-dcap-sys = { path = "sys" }
mc-sgx-urts = { path = "../urts" }

[dev-dependencies]
test_enclave = { path = "../test_enclave" }

[features]
default = []
# TODO rebase this on https://github.com/mobilecoinfoundation/sgx/pull/14 to get
#   the features from the `mc-sgx-dcap-sys` crate
generate = []
verify = []
