[package]
name = "constant_time_derive"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.8"
quote = "1.0"
subtle = { version = "2.4.0", default-features = false }
syn = "1.0"
