[workspace]
resolver = "2"
members = [
    "capable",
    "capable/sys",
    "capable/sys/types",
    "capable/types",
    "core/build",
    "core/sys/types",
    "core/types",
    "dcap/ql/sys",
    "dcap/ql/sys/types",
    "dcap/quoteverify/sys",
    "dcap/quoteverify/sys/types",
    "dcap/quoteverify/types",
    "dcap/sys/types",
    "dcap/tvl/sys",
    "tcrypto/sys",
    "tcrypto/sys/types",
    "trts/sys",
    "tservice/sys",
    "tservice/sys/types",
    "tservice/types",
    "tstdc/sys",
    "tstdc/sys/types",
    "urts",
    "urts/sys",
    "urts/sys/types",
    "util",
]
exclude = [
    "test_enclave",
]

[profile.dev]
opt-level = 0
lto = true

[profile.release]
opt-level = 3
rpath = false
lto = true
debug-assertions = false
overflow-checks = false
