[package]
name = "mc-sgx-dcap-quoteverify-sys-types"
version = "0.6.0"
authors = { workspace = true }
# See https://crates.io/category_slugs for valid categories
categories = ["external-ffi-bindings", "hardware-support", "no-std"]
description = "FFI type definitions used by the `sgx_dcap_quoteverify` library."
edition = { workspace = true }
# See https://crates.io/keywords for the common keywords
keywords = ["ffi", "sgx", "no-std"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }

[lib]
doctest = false

[dependencies]
mc-sgx-dcap-sys-types = { path = "../../../sys/types", version = "=0.6.0" }

[build-dependencies]
bindgen = "0.65.1"
cargo-emit = "0.2.1"
mc-sgx-core-build = { path = "../../../../core/build", version = "=0.6.0" }
