[package]
name = "mc-sgx-urts"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-urts-sys = { path = "../urts_sys" }

[features]
sw = []
default = ["sw"]

[dev-dependencies]
test_enclave = { path = "../test_enclave" }