[package]
name = "test_enclave"
version = "0.1.0"
edition = "2021"

[dependencies]
mc-sgx-urts-sys-types = { path = "../urts_sys_types" }

[features]
hw = []
default = []

[build-dependencies]
cargo-emit = "0.2.1"
cc = "1.0.73"
bindgen = "0.59.2"
