[package]
name = "mc-sgx-dcap-sys-types"
version = "0.6.0"
authors = ["MobileCoin"]
categories = ["external-ffi-bindings", "hardware-support", "no-std"]
description = "FFI type definitions for the SGX DCAP libraries."
edition = "2021"
keywords = ["ffi", "sgx", "no-std"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/mobilecoinfoundation/sgx"
rust-version = "1.62.1"

[lib]
doctest = false

[dependencies]
constant_time_derive = { path = "../../../constant_time_derive", version = "0.1.0" }
mc-sgx-core-sys-types = { path = "../../../core/sys/types", version = "=0.6.0" }
subtle = { version = "2.4.0", default-features = false }

[build-dependencies]
bindgen = "0.65.1"
mc-sgx-core-build = { path = "../../../core/build", version = "=0.6.0" }
