[package]
name = "mc-sgx-dcap-quoteverify-types"
version = "0.6.0"
authors = { workspace = true }
# See https://crates.io/category_slugs for valid categories
categories = ["api-bindings", "hardware-support"]
description = "Rust wrapper for `dcap_quoteverify` types."
edition = { workspace = true }
# See https://crates.io/keywords for the common keywords
keywords = ["ffi", "sgx"]
license = { workspace = true }
readme = "README.md"
repository = { workspace = true }
rust-version = { workspace = true }

[dependencies]
mc-sgx-core-types = { path = "../../../core/types", version = "=0.6.0" }
mc-sgx-dcap-quoteverify-sys-types = { path = "../sys/types", version = "=0.6.0" }

[dev-dependencies]
yare = "1.0.2"
