name: ci

on:
  push:
    branches:
      - 'main'
  pull_request:

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"
  MC_NIGHTLY: "nightly-2023-03-08"

jobs:
  lint:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - uses: r7kamura/rust-problem-matchers@v1
      - run: cargo fmt --all -- --check
      - uses: xt0rted/markdownlint-problem-matcher@v2
      - uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: "**/*.md"

  crev:
    runs-on: ubuntu-22.04
    # Override errors here, eventually we'd like to start failing PRs based on this
    continue-on-error: true
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - run: cargo check
      - name: Initialize Cargo Crev
        run: |-
          cargo install cargo-crev || true
          cargo crev trust --level high --no-commit https://github.com/mobilecoinfoundation/crev-proofs
      - name: Run Cargo Crev
        id: cargo-crev
        run: |
          set +e

          export MARKER=$RANDOM
          echo "UNREVIEWED_DEPENDENCIES<<EOF${MARKER}" >> $GITHUB_OUTPUT

          # GH does not like colors in crev output
          export TERM=xterm-mono

          # - Get a TSV-formatted table of dependencies without recorded reviews
          # - Skip any "local" dependencies
          # - Convert the table to GHF markdown
          # - Sort descending by the "LoC" value (first column preceeds first pipe)
          
          cargo crev crate verify \
              --for-id vMr-9g5KzKQLsCpkp1tc8o7AR6a0OptjOICjf7NMyHE \
              --show-all \
              --skip-indirect \
              --skip-verified \
              --skip-known-owners \
              --trust medium \
              --thoroughness medium \
              --understanding medium \
              --redundancy 2 | \
            grep -v '^local ' | \
            awk '{printf("| %s | %s | %s | %s | %s | %s | %s |\n", $14, $15, $2, $10, $11, $12, $13)}' | \
            sort -t\| -n -k5 | \
            tee /dev/stderr >> $GITHUB_OUTPUT
          STATUS=$?

          echo "EOF${MARKER}" >> $GITHUB_OUTPUT
          
          set -e
          
          # TODO: Once we're ready to start failing PRs for lack of dependency reviews
          # exit $STATUS 
          exit 0
        shell: bash
      - uses: mshick/add-pr-comment@v2
        with:
          message: |
            #### :x: Unreviewed dependencies found
            
            | Crate | Version | Reviews (N/2) | LoC | Left-Pad Index | Geiger | Flags |
            | ----- | ------- | ------------- | --- | -------------- | ------ | ----- |
            ${{ steps.cargo-crev.outputs.UNREVIEWED_DEPENDENCIES }}

  deny:
    strategy:
      matrix:
        check:
          - advisories
          - bans licenses sources
    runs-on: ubuntu-22.04
    needs:
      - "lint"
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - uses: EmbarkStudios/cargo-deny-action@v1
        with:
          command: check ${{ matrix.check }}

  sort:
    runs-on: ubuntu-22.04
    needs:
      - "lint"
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo install cargo-sort
      - run: cargo sort --workspace --check >/dev/null

  clippy:
    needs:
      - "lint"
    strategy:
      matrix:
        rust:
          - stable
          - beta
    runs-on: ubuntu-22.04
    # Prevent beta warnings from causing CI failure
    continue-on-error: ${{ matrix.rust == 'beta' }}
    steps:
      - uses: actions/checkout@v3
      - uses: mobilecoinfoundation/actions/dcap-libs@main
        with:
          version: 1.15.100.3-jammy1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          components: clippy
      - uses: r7kamura/rust-problem-matchers@v1
      - run: cargo +${{ matrix.rust }} clippy --all --all-features -- -D warnings

  # All our crates are supposed to work on x86_64
  test-intel:
    strategy:
      fail-fast: false
      matrix:
        rust:
          - stable
          - beta
    runs-on: ubuntu-22.04
    needs:
      - "lint"
    steps:
      - run: env
      - uses: actions/checkout@v3
      - uses: mobilecoinfoundation/actions/sgxsdk@main
        with:
          version: 2.18.100.3
      - uses: mobilecoinfoundation/actions/dcap-libs@main
        with:
          version: 1.15.100.3-jammy1
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: r7kamura/rust-problem-matchers@v1
      - run: env
      - name: cargo test
        run: |
          unset SGX_AESM_ADDR
          cargo +${{ matrix.rust }} test --release --features="sim alloc"

<<<<<<< HEAD
  # Only the types crates are intended to be used on non-intel platforms
  test-crossplatform:
    needs:
      - "lint"
=======
  # Unit-test types crates on windows/mac
  test-desktop:
>>>>>>> 8804d00 (Just do windows/mac for now)
    strategy:
      fail-fast: false
      matrix:
        os:
          - windows-latest
          - macos-latest
          # FIXME: Add self-hosted M1 runner until https://github.com/github/roadmap/issues/528
          #        is fixed.
        rust:
          - stable
          - beta
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo test
        shell: bash
        run: |-
          cargo +${{ matrix.rust }} test \
            --release \
            --features="alloc" \
            -p mc-sgx-capable-sys-types \
            -p mc-sgx-capable-types \
            -p mc-sgx-core-sys-types \
            -p mc-sgx-core-types \
            -p mc-sgx-dcap-ql-sys-types \
            -p mc-sgx-dcap-ql-types \
            -p mc-sgx-dcap-quoteverify-sys-types \
            -p mc-sgx-dcap-quoteverify-types \
            -p mc-sgx-dcap-sys-types \
            -p mc-sgx-dcap-types \
            -p mc-sgx-tcrypto-sys-types \
            -p mc-sgx-tservice-sys-types \
            -p mc-sgx-tservice-types \
            -p mc-sgx-tstdc-sys-types \
            -p mc-sgx-urts-sys-types

  # Run unit tests on platforms which do not support alloc
  test-embedded:
    needs:
      - "lint"
    strategy:
      matrix:
        target:
          - thumbv6m-none-eabi
          - thumbv7m-none-eabi
          - thumbv8m.main-none-eabi
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ env.MC_NIGHTLY }}
          targets: ${{ matrix.target }},x86_64-unknown-linux-gnu
          components: rust-src
      - uses: r7kamura/rust-problem-matchers@v1
      - name: cargo build
        # Some notes on this build command:
        # - The vendored headers are used to get the necessary DCAP headers
        # - The vendored `tlibc` is used to get a compilable `time.h` for the target.
        # - In the unlikely event that the target was installed with rustup, this would error out with
        #   duplicate core symbols due to `-Z build-std=core`.
        run: |-
          CFLAGS="-isystem${GITHUB_WORKSPACE}/core/build/headers -isystem${GITHUB_WORKSPACE}/core/build/headers/tlibc" \
          cargo +${{ env.MC_NIGHTLY }} build \
            -Z build-std=core \
            --target ${{ matrix.target }} \
            --release \
            -p mc-sgx-capable-sys-types \
            -p mc-sgx-capable-types \
            -p mc-sgx-core-sys-types \
            -p mc-sgx-core-types \
            -p mc-sgx-dcap-ql-sys-types \
            -p mc-sgx-dcap-ql-types \
            -p mc-sgx-dcap-quoteverify-sys-types \
            -p mc-sgx-dcap-quoteverify-types \
            -p mc-sgx-dcap-sys-types \
            -p mc-sgx-dcap-types \
            -p mc-sgx-tcrypto-sys-types \
            -p mc-sgx-tservice-sys-types \
            -p mc-sgx-tservice-types \
            -p mc-sgx-tstdc-sys-types \
            -p mc-sgx-urts-sys-types

  doc:
    runs-on: ubuntu-22.04
    needs:
      - "lint"
    strategy:
      matrix:
        rust:
          - stable
          - beta
    # Prevent beta warnings from causing CI failure
    continue-on-error: ${{ matrix.rust == 'beta' }}
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - uses: r7kamura/rust-problem-matchers@v1
      - run: cargo +${{ matrix.rust }} doc --release --no-deps --features sim

  coverage:
    runs-on: ubuntu-22.04
    needs:
      - "lint"
    steps:
      - uses: actions/checkout@v3
      - uses: mobilecoinfoundation/actions/sgxsdk@main
        with:
          version: 2.18.100.3
      - uses: mobilecoinfoundation/actions/dcap-libs@main
        with:
          version: 1.15.100.3-jammy1
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: llvm-tools-preview
      - uses: taiki-e/install-action@cargo-llvm-cov
      - name: Run tests with coverage
        # For some reason `SGX_AESM_ADDR` is set to 1 in the github runners.
        # Not seeing it documented here, https://github.com/actions/runner-images/blob/main/images/linux/Ubuntu2004-Readme.md
        # We can't just set to 0 or "" as the SGX code looks for it being set, not what the value is :(
        # The FFI bindings crates always report 100% because they have no code
        run: |-
          unset SGX_AESM_ADDR
          cargo llvm-cov \
            --features "sim alloc" \
            --ignore-filename-regex '\/sys/src/lib\.rs' \
            --workspace \
            --lcov \
            --output-path lcov.info
      - uses: codecov/codecov-action@v3
        with:
          files: lcov.info

  notify:
    runs-on: ubuntu-latest
    if: failure() && ${{ github.event_name }} == 'push'
    needs:
      - "lint"
      - "deny"
      - "sort"
      - "crev"
      - "clippy"
      - "test"
      - "test-intel"
      - "test-desktop"
      - "build-embedded"
      - "doc"
      - "coverage"
    steps:
      - name: Notify Discord on failure
        uses: sarisia/actions-status-discord@v1
        with:
          username: "Github Actions"
          status: Failure
          nodetail: true
          title: "Workflow: ${{ github.workflow }}"
          url: ${{ github.repository_url }}/actions/runs/${{ github.run_id }}
          description: |
            [@${{ github.pusher }}](${{ github.url }}/${{ github.pusher }}] was the last one to touch ${{ github.repository }}, is all I'm saying...
          avatar_url: "https://media0.giphy.com/media/oe33xf3B50fsc/200.gif"
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
