name: Lint
on:
  pull_request:
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - run: cargo fmt --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - uses: ./.github/actions/dcap-libs
      - run: cargo clippy --all --all-features --locked -- -D warnings
  nono:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup rust toolchain
        run: rustup show
      - name: install nono
        run: cargo install cargo-nono
      # `mc-sgx-quote-verify` should be `no_std`, but it isn't yet.  See #34
      - run: |
          cargo metadata --no-deps --format-version=1 | \
            jq -r '.packages[].name' | \
            grep -v -e mc-sgx-core-build -e mc-sgx-dcap-quoteverify-sys -e mc-sgx-dcap-ql-sys -e mc-sgx-quote-verify -e mc-sgx-urts -e mc-sgx-capable-sys | \
            xargs -n1 sh -c 'cargo nono check --package $0 || exit 255'
  markdown-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: xt0rted/markdownlint-problem-matcher@v1
      - name: Install markdown lint
        run: npm install -g markdownlint-cli@0.32.1
      - run: markdownlint --disable 'MD013' "**/*.md"
