name: panic-abort

on:
  pull_request:
    paths:
      - "trusted/panic/abort/**"
      - "Cargo.*"

defaults:
  run:
    working-directory: "trusted/panic/abort"

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        - nightly-2021-07-21
        - nightly
      target:
        - x86_64-unknown-linux-gnu
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
          profile: minimal
      - run: cargo build --release --target ${{ matrix.target }}

