name: rust

on:
  pull_request:
    paths:
      - 'trusted/**'
    branches:
      - 'main'
      - 'develop'
      - 'feature/**'

defaults:
  run:
    working-directory: "trusted"

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: [self-hosted, Linux, large]
    container: mobilecoin/rust-sgx-base:latest
    steps:
      - uses: actions/checkout@v3
      # actions-rs/toolchain does not support the newer toml file format
      # see https://github.com/actions-rs/toolchain/issues/126
      - name: Setup rust toolchain
        run: rustup show
      - run: cargo build --release 
  # No tests for now.  
  # `cargo test` needs std, panic is no_std
  # Also trts needs built with the custom target triple to link 
