name: Workspace
on:
  pull_request:
    paths-ignore:
      - README.md

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: rustfmt
          override: true
          profile: minimal
      # actions-rs/cargo does not support the `working-directory` argument,
      # see https://github.com/actions-rs/cargo/issues/6
      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --manifest-path trusted/Cargo.toml --all -- --check
  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly
          components: clippy
          override: true
          profile: minimal
      - run: cargo clippy --all --all-features -- -D warnings
        working-directory: ./trusted
